# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MediaPipeHands', :podspec => 'https://github.com/szotp-lc/HandTracker/releases/download/1.4/MediaPipeHands.podspec'


end
